/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SoftwareRouteImport } from './routes/software'
import { Route as RoboticsRouteImport } from './routes/robotics'
import { Route as ContactRouteImport } from './routes/contact'
import { Route as AcademicsRouteImport } from './routes/academics'
import { Route as AboutRouteImport } from './routes/about'
import { Route as IndexRouteImport } from './routes/index'

const SoftwareRoute = SoftwareRouteImport.update({
  id: '/software',
  path: '/software',
  getParentRoute: () => rootRouteImport,
} as any)
const RoboticsRoute = RoboticsRouteImport.update({
  id: '/robotics',
  path: '/robotics',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactRoute = ContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => rootRouteImport,
} as any)
const AcademicsRoute = AcademicsRouteImport.update({
  id: '/academics',
  path: '/academics',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/academics': typeof AcademicsRoute
  '/contact': typeof ContactRoute
  '/robotics': typeof RoboticsRoute
  '/software': typeof SoftwareRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/academics': typeof AcademicsRoute
  '/contact': typeof ContactRoute
  '/robotics': typeof RoboticsRoute
  '/software': typeof SoftwareRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/academics': typeof AcademicsRoute
  '/contact': typeof ContactRoute
  '/robotics': typeof RoboticsRoute
  '/software': typeof SoftwareRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/academics'
    | '/contact'
    | '/robotics'
    | '/software'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/about' | '/academics' | '/contact' | '/robotics' | '/software'
  id:
    | '__root__'
    | '/'
    | '/about'
    | '/academics'
    | '/contact'
    | '/robotics'
    | '/software'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutRoute: typeof AboutRoute
  AcademicsRoute: typeof AcademicsRoute
  ContactRoute: typeof ContactRoute
  RoboticsRoute: typeof RoboticsRoute
  SoftwareRoute: typeof SoftwareRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/software': {
      id: '/software'
      path: '/software'
      fullPath: '/software'
      preLoaderRoute: typeof SoftwareRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/robotics': {
      id: '/robotics'
      path: '/robotics'
      fullPath: '/robotics'
      preLoaderRoute: typeof RoboticsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contact': {
      id: '/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof ContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/academics': {
      id: '/academics'
      path: '/academics'
      fullPath: '/academics'
      preLoaderRoute: typeof AcademicsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutRoute: AboutRoute,
  AcademicsRoute: AcademicsRoute,
  ContactRoute: ContactRoute,
  RoboticsRoute: RoboticsRoute,
  SoftwareRoute: SoftwareRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
